# Generated by Django 5.0.2 on 2024-03-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_class',
            name='short_description',
        ),
    ]
