# Generated by Django 5.0.2 on 2024-03-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_music_class_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_class',
            name='image',
            field=models.ImageField(upload_to='static/coverimg/'),
        ),
    ]
