# Generated by Django 5.0.2 on 2024-03-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
