# Generated by Django 5.0.2 on 2024-03-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0012_music_class_genres'),
    ]

    operations = [

    ]
