# Generated by Django 5.0.2 on 2024-03-15 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0013_alter_music_class_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_class',
            old_name='Genres',
            new_name='genres',
        ),
        
    ]
