# Generated by Django 5.0.2 on 2024-03-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0014_rename_genres_music_class_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_class',
            name='artist',
        ),
    ]
