# Generated by Django 5.0.2 on 2024-03-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0015_remove_music_class_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_class',
            name='viewer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
