# Generated by Django 5.0.2 on 2024-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0018_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_class',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='music_class',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
