# Generated by Django 5.0.2 on 2024-03-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0019_music_class_artist_name_music_class_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='music_class',
            name='viewer',
        ),
        migrations.AddField(
            model_name='music_class',
            name='viewer',
            field=models.ManyToManyField(blank=True, related_name='post_view', to='musics.ipmodel'),
        ),
    ]
