# Generated by Django 5.0.2 on 2024-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0020_ipmodel_remove_music_class_viewer_music_class_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_class',
            name='viewer',
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
        migrations.AddField(
            model_name='music_class',
            name='viewer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
