# Generated by Django 5.0.2 on 2024-03-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0021_remove_music_class_viewer_delete_ipmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_class',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
