# Generated by Django 5.0.2 on 2024-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0023_remove_music_class_likes_music_class_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_class',
            name='likes',
        ),
        migrations.AddField(
            model_name='music_class',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
