# Generated by Django 4.1.7 on 2024-03-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0025_artist_remove_music_class_artist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_class',
            old_name='artist_name',
            new_name='author',
        ),
    ]
