# Generated by Django 4.1.7 on 2024-03-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0026_rename_artist_name_music_class_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_class',
            name='likes',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='music_class',
            name='viewer',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
