# Generated by Django 4.1.7 on 2024-03-29 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0027_alter_music_class_likes_alter_music_class_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_class',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music_class',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_music_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
