# Generated by Django 4.1.7 on 2024-03-29 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0028_alter_music_class_artist_alter_music_class_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_class',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.artist'),
        ),
        migrations.AlterField(
            model_name='music_class',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music_class',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='music_class',
            name='viewer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
