# Generated by Django 4.1.7 on 2024-03-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0029_alter_music_class_artist_alter_music_class_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_class',
            name='author',
        ),
    ]
