# Generated by Django 4.1.7 on 2024-04-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0035_alter_article_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
