# Generated by Django 4.1.7 on 2024-04-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0036_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_class',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
