# Generated by Django 4.1.7 on 2024-04-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0037_alter_music_class_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(upload_to='artist_images/'),
        ),
    ]
